### ISSUE TITLE
Run Elixir Fragment button doesn't work

### ISSUE THREAD

**Issue by bigardone** [kickinespresso/elixir_fiddle_issues#7]
Hi!
I'm trying to run a fragment using the button underneath the script preview, but it does not show the result.

![image](https://user-images.githubusercontent.com/1090272/40351553-fe32e874-5dac-11e8-9aae-30c4f8f67204.png)

If I click on the one on the left, underneath de title it does run it:

![image](https://user-images.githubusercontent.com/1090272/40351620-24a20f8a-5dad-11e8-80e8-7cf995b90ebc.png)

This is the fragment https://elixirfiddle.com/fragments/25

Great project BTW, keep it up!

**Comment by cdesch** [comment]
Hi @bigardone - thanks for reporting the issue. I fixed the issue (`1.0.7`) and pushed up the changes. Please let me know if you have any other feedback!
